# Generated by Django 3.2.8 on 2021-11-08 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityRequired', models.IntegerField(default=1)),
                ('quantityRemaining', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=12, null=True)),
                ('justification', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('prov', 'Healthcare Provider'), ('univ', 'University'), ('fac', 'Faculty'), ('dept', 'Department'), ('rc', 'Research Centre'), ('team', 'Organizational team'), ('govt', 'Government'), ('edu', 'Educational Institute'), ('crs', 'Clinical Research Sponsor'), ('cg', 'Community Group'), ('bus', 'Non-Healthcare Business or Corporation'), ('other', 'Other')], max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('BILL', 'Billing'), ('ADMIN', 'Administrative'), ('RES', 'Research Centre'), ('EDU', 'Education Provider'), ('SUPP', 'Supplier')], max_length=12)),
                ('addressType', models.CharField(choices=[('PO', 'postal'), ('PH', 'physical'), ('BO', 'both')], default='PH', max_length=2)),
                ('address', models.CharField(max_length=1000, verbose_name='address')),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(max_length=25)),
                ('postalCode', models.CharField(default='00000', max_length=12, verbose_name='post code')),
                ('country', models.CharField(default='MY', max_length=2)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composition', to='projects.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('voteID', models.CharField(max_length=25)),
                ('projectNumber', models.CharField(max_length=25)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subjectName', models.CharField(max_length=120, null=True, verbose_name='full name')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='salutations or honorifics')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=1)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('T', 'Transgendered'), ('U', 'Unknown'), ('O', 'Others')], max_length=1, null=True)),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('ethnicity', models.CharField(blank=True, choices=[('ML', 'Malay'), ('CH', 'Chinese'), ('IN', 'Indian'), ('IB', 'Iban'), ('KM', 'Kadazan Murut'), ('IM', 'West Malaysia indigenous'), ('IS', 'Other East Malaysia indigenous'), ('EA', 'East Asian'), ('HI', 'Hispanic'), ('PI', 'Pacific Islander'), ('AR', 'Arab'), ('PE', 'Persian'), ('UN', 'Unspecified')], max_length=2, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(null=True)),
                ('voteNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'Principal researcher'), ('co', 'Co researcher'), ('student', 'Research student'), ('so', 'Scientific officer'), ('employee', 'Company employee')], max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='projects.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=25)),
                ('specification', models.JSONField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.item')),
                ('project', models.ManyToManyField(through='projects.Consumable', to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(through='projects.SubjectRole', to='projects.Subject'),
        ),
        migrations.CreateModel(
            name='OrganizationContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'phone'), ('fax', 'fax'), ('email', 'E-mail'), ('url', 'url'), ('sms', 'sms')], max_length=5)),
                ('value', models.CharField(max_length=255)),
                ('use', models.CharField(choices=[('T', 'temporary'), ('O', 'old'), ('B', 'billing'), ('E', 'enquiry')], default='E', max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_contact_points', to='projects.organization')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.organization'),
        ),
        migrations.CreateModel(
            name='Initiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=12)),
                ('revNo', models.IntegerField(default=0)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('listOfSuppliers', models.JSONField(null=True)),
                ('preparedDate', models.DateField(null=True)),
                ('InitiationDate', models.DateField(null=True)),
                ('approvalDateSupervisor', models.DateField(null=True)),
                ('approvalDateHOD', models.DateField(null=True)),
                ('rfqSendDate', models.DateField(null=True)),
                ('rfqCloseDate', models.DateField(null=True)),
                ('approvedByHOD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='projects.subject')),
                ('approvedBySupervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='projects.subject')),
                ('initiatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_initiated', to='projects.subject')),
                ('lineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.specification')),
                ('preparedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_prepared', to='projects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idValue', models.CharField(max_length=30)),
                ('idType', models.CharField(choices=[('NR', 'National registration id'), ('PP', 'Passport id'), ('EI', 'Employment id')], max_length=5)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='projects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'phone'), ('mobile', 'mobile'), ('fax', 'fax'), ('email', 'E-mail'), ('url', 'url'), ('sms', 'sms')], max_length=12)),
                ('value', models.CharField(max_length=255)),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('P', 'personal')], max_length=1)),
                ('rank', models.PositiveSmallIntegerField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='projects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='projects.specification'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('B', 'billing')], max_length=1)),
                ('type', models.CharField(choices=[('PO', 'postal'), ('PH', 'physical'), ('BO', 'both')], default='PH', max_length=2)),
                ('text', models.CharField(max_length=1000, verbose_name='address')),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(max_length=25)),
                ('postalCode', models.CharField(default='00000', max_length=12, verbose_name='post code')),
                ('country', models.CharField(default='MY', max_length=2)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='projects.subject')),
            ],
        ),
    ]
