# Generated by Django 3.2.8 on 2021-11-08 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initiation_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiation',
            name='InitiationDate',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='approvalDateHOD',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='approvalDateSupervisor',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='approvedByHOD',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='approvedBySupervisor',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='initiatedBy',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='preparedBy',
        ),
        migrations.RemoveField(
            model_name='initiation',
            name='preparedDate',
        ),
        migrations.AlterField(
            model_name='initiation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project'),
        ),
        migrations.CreateModel(
            name='InitiationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subject')),
            ],
        ),
    ]
