# Generated by Django 3.2.8 on 2021-11-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211108_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiationrole',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project'),
            preserve_default=False,
        ),
    ]
