# Generated by Django 3.2.8 on 2021-11-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_initiationrole_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiationrole',
            name='project',
        ),
        migrations.AddField(
            model_name='initiationrole',
            name='initiation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.initiation'),
            preserve_default=False,
        ),
    ]
