# Generated by Django 3.2.8 on 2021-11-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211108_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='consumables',
            field=models.ManyToManyField(through='projects.Consumable', to='projects.Specification'),
        ),
        migrations.AlterField(
            model_name='initiation',
            name='lineItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.consumable'),
        ),
    ]
